#!/bin/bash

# can't just use an svg cause, unlike Firefox, Chrome has had a bug since 2009 where extension icons don't recognize svgs
# source: https://bugs.chromium.org/p/chromium/issues/detail?id=29683

echo "Creating pngs from svg"

for size in 16 32 48 64 96 128; do
	inkscape icons/icon.svg -e icons/icon_"$size".png -w "$size" -h "$size"
done
